pipeline{

 agent any



stages{

 stage('git clone'){

 steps{

 git 'https://github.com/Neikl/salesforce-demo.git'

 }

 }

 stage('Running ANT scripts'){

 steps{

 sh "cd sample && ant retrieveUnpackaged -v && ant deployUnpackaged -v"

 }

 }

 stage('Chatter Notifier'){

 steps{

 chatterPost body: "This is a Chatter post from a pipeline! ${env.JOB_NAME} ${env.BUILD_DISPLAY_NAME}", credentialsId: 'team.sfdc.user'

 }

 } 
 
 stage('Production Server status'){

 steps{

 sh "curl -s --head  --request GET  https://data-energy-8745-dev-ed.cs114.my.salesforce.con | grep '200'"

 }

 }
 
 }

 }
