pipeline{

 agent any

stages{
	
 stage('git clone source'){

 steps{

 git 'https://github.com/Neikl/purealoe-lwc.git'

 }

 }

 stage('Souce Code Analysis'){

 steps{

 sh "sonar-scanner \
  -Dsonar.projectKey=salesforce-demo \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://192.168.0.146:9000 \
  -Dsonar.login=a1e738c7b01ce1df11e6cf8e31308ac4b1287f32"

 }

 }

 stage('git clone'){

 steps{

 git 'https://github.com/Neikl/salesforce-demo.git'

 }

 }

 stage('Running ANT scripts'){

 steps{

 sh "cd sample && ant retrieveUnpackaged -v && ant deployUnpackaged -v"

 }

 }

 stage('Production Server status'){

 steps{

 sh "curl -s --head  --request GET  https://data-energy-8745-dev-ed.cs114.my.salesforce.com | grep '200'"

 }

 }	
	
 stage('Chatter Notifier'){

 steps{

 chatterPost body: "This is a Chatter post from a pipeline! ${env.JOB_NAME} ${env.BUILD_DISPLAY_NAME}", credentialsId: 'team.sfdc.user'

 }

 } 
 
 }

 }
